spring:
  application:
    name: auth
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5437/authdb
    password: test
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8084
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    oauth:
      client-id: client-id
      client-secret: client-secret
      scopes: read,write
    path: '/swagger-ui.html'