version: '3'
services:
  db:
    image: postgres:16.1
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: bookingsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
